### ISSUE TITLE
`*` will be translated to wildcard in bash and other terminals and so on.

### ISSUE THREAD

**Issue by Xuanyiyiren** [ShiqiYu/CPP#51]
I am an undergraduage student major in physics, and I am new to computer science. I am recently learning C++ course given by Prof.Yu and trying to finish Yu's projects.

But in the first project, Prof.Yu give an example of the program like this
```bash
$./calculator 2 + 3
2 + 3 = 5
$./calculator 2 - 3
2 - 3 = -1
$./calculator 2 * 3
2 * 3 = 6
$./calculator 2 / 3
2 / 3 = 0.66666667
```

However, the terminals will treat * as wildcard, and when I input "2 * 3", I find the `main` function get more then 4 argements, and most of them are files' names in the same content.

How do I solve this question? My solution is using `x` to replace `*`, is that a good adjustment?

**Comment by ShiqiYu** [comment]
Yes, you can do in that way.
